pipeline:
  name: Fullstack-App-Deploy
  identifier: FullstackAppDeploy
  projectIdentifier: Default_Project
  orgIdentifier: default
  stages:
    - stage:
        name: Infrastructure
        identifier: Infrastructure
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: TF Plan
                  spec:
                    configuration:
                      type: Inline
                      spec:
                        workingDirectory: terraform/environments/prod