pipeline:
  name: Enterprise-IaC-Pipeline
  identifier: EnterpriseIaCPipeline
  projectIdentifier: Default_Project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Terraform-Deploy
        identifier: TerraformDeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Terraform
          infrastructure:
            environmentRef: prod
            infrastructureDefinition:
              type: AwsCloud
              spec:
                connectorRef: aws-connector
                region: us-east-1
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: Plan
                  identifier: Plan
              - step:
                  type: TerraformApply
                  name: Apply
                  identifier: Apply
        tags: {}