version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_FE
  build:
    commands:
      - docker build -t $ECR_REPO_FE:latest ./frontend
  post_build:
    commands:
      - docker push $ECR_REPO_FE:latest
      - printf '[{"name":"frontend","imageUri":"%s"}]' $ECR_REPO_FE:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json