version: 0.2
phases:
  install:
    commands:
      - tfenv install 1.5.0
      - tfenv use 1.5.0
  build:
    commands:
      - cd terraform
      - terraform init
      - terraform plan -var-file="environments/dev/terraform.tfvars" -out=tfplan
      - terraform apply -auto-approve tfplan