version: 0.2
phases:
  install:
    commands:
      - tf_version="1.5.0"
      - wget https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip
      - unzip terraform_${tf_version}_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - cd terraform/environments/dev
      - terraform init
  build:
    commands:
      - terraform plan -out=tfplan
  post_build:
    commands:
      - terraform apply -auto-approve tfplan